User array literal instead of list().
Needed because the code was giving this error:

TypeError: '<' not supported between instances of 'str' and 'int'